---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vizier-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-vizier-operator
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-vizier-operator
        plane: control
    spec:
      serviceAccountName: {{ .Release.Name }}-pixie-operator-service-account
      containers:
      - name: app
        image: gcr.io/pixie-oss/pixie-prod/operator/operator_image:0.0.28
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/os
                operator: Exists
              - key: kubernetes.io/os
                operator: In
                values:
                - linux
            - matchExpressions:
              - key: beta.kubernetes.io/os
                operator: Exists
              - key: beta.kubernetes.io/os
                operator: In
                values:
                - linux
